# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
format = "$directory$git_branch$git_status$python$character "
# format = "$directory $character"
# format = "$directory $character $git_branch $git_commit $git_state $git_metrics $git_status"
add_newline = false
# add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true



[directory]
truncation_length = 3
style = "white"

[python]
# Show Python version and virtual environment info
# format = "$symbol$version$virtualenv "
format = "$symbol$virtualenv "
symbol = " "
# detect_virtualenvs = true

# [python.virtualenv]
# format = "(${name})"
# style = "yellow"

